[sdl]
windowresolution=640x480
output=surface
usescancodes=false

[cpu]
cycles=max

[dos]
xms=true

[autoexec]
mount c /home/jzatopa/.openclaw/workspace/matrix-cubed-re/generated/liveplay/first_map_capture/game
c:
start.exe
